---
title: Wild Boar are from Mars
subtitle: Do males move more than females?
author: Lizzy Nickell
output: html_document
---

```{r, echo = FALSE, warning=FALSE, message=FALSE}
#Housekeeping:

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

#Please load the following Libraries:
library(ComputationalMovementAnalysisData)
library(sf)
library(tidyverse)
library(psych)
library(ggpubr)
library(dplyr)
library(tmap)
```

## Abstract

There are many physical and behavioral differences between male and female wild boars. Females are typically smaller, and stay together in herds with other females and young. Males, on the other hand, wander larger territories, avoiding other males, and only interacting with females during mating season. We wanted to know if this difference in behavior is noticeable in their movement patterns. Using current data and multiple methods, we have found no differences in the movement patterns. While they may act differently, one sex does not move more than the other.

## Introduction

    The wild boar (Sus scrofa) is a highly adaptable species native to Europe and Asia and introduced to North America. They are highly invasive in North America, and considered pests in most of Europe and Asia. As such, numerous projects have been put in place to track the movements of wild boar and monitor efforts to repel them from croplands. 

    Wild boars are a dimorphic species. Males are 20% larger than females, and are solitary for the majority of the year (Wickline, 2014). Females travel in herds anywhere from 6 to 100 individuals with piglets, juveniles, and males up to 2 years old (Wickline, 2014). Females protect offspring, sometimes leaving piglets with a single female while others go off to forage. It has been estimated that homeranges for females are 500-1,000 ha, while males have a homerange of 1,000-2,000 ha (Kueling and Leus, 2019). 

    Nineteen wild boar were tagged and monitored between the years of 2014 and 2016. Six of the boars were adult males, and the rest were adult females. Two main site locations were determeined by looking at the center of the the pig's locations: Bern and Aargau. Some of the pigs were captured multiple times and given new collars, but their ID was kept the same. Depending on the pig, and time of year, locations were taken at different sampling ratios. Pigs with enough data were used for this analysis. 

## Material and Methods

Nineteen wild boar were tagged and monitored between the years of 2014 and 2016. Six of the boars were adult males, and the rest were adult females. Two main site locations were determeined by looking at the center of the the pig's locations: Bern and Aargau. Some of the pigs were captured multiple times and given new collars, but their ID was kept the same. Depending on the pig, and time of year, locations were taken at different sampling ratios. Pigs with enough data were used for this analysis.

Two methods were used to analyze the motion of the pigs and compare them by sex. The first was a traditional bounding box method, taking the extreme coordinates in each direction and creating a box.

## Results

<!-- the following is just a placeholder text, remove it!-->

Philosophy oneself passion play fearful self noble zarathustra deceptions sexuality. Endless ocean of oneself dead ocean. Selfish decrepit.

## Discussion

<!-- the following is just a placeholder text, remove it!-->

Justice convictions spirit sexuality insofar free marvelous joy. Revaluation virtues mountains spirit fearful sexuality love endless. Society intentions will noble burying aversion moral. Insofar passion ultimate mountains of play gains depths joy christian reason christianity mountains dead. Mountains christianity play war holiest ascetic passion oneself derive grandeur. Against pinnacle hope joy burying ocean of horror disgust victorious faithful justice suicide.
